# Generated by Django 2.1.5 on 2019-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], default='draft', max_length=7),
        ),
    ]
